library(dplyr)
data1 <- read.csv('./data/indiana_county_level_mobility_time_series_data_formatted_7.csv')
df1 <- data.frame(select_if(data1, is.factor))

main <- function() {
  # model <- df1$date ~ df1$cases + df1$deaths + df1$lat + df1$long + df1$avg_cases_last_week + df1$avg_deaths_last_week + df1$avg_cases_last_2_weeks + df1$avg_deaths_last_2_week + df1$std_cases_last_week + df1$std_deaths_last_week + df1$std_cases_last_2_weeks + df1$std_deaths_last_2_weeks + df1$median_gross_rent + df1$average_household_size + df1$building_permits_number + df1$percent_households_with_computer + df1$percent_households_with_broadband_internet + df1$dollars_per_capita_income_in_past_12_months_2018 + df1$population_per_square_mile + df1$median_household_income + df1$percent_housing_units_in_multi_unit_structures + df1$percent_under_65_without_health_insurance + df1$percent_under_65_with_disability + df1$retail_and_recreation_percent_change_from_baseline + df1$grocery_and_pharmacy_percent_change_from_baseline + df1$parks_percent_change_from_baseline + df1$transit_stations_percent_change_from_baseline + df1$workplaces_percent_change_from_baseline + df1$residential_percent_change_from_baseline + df1$mobility_by_driving + df1$mobility_by_walking + df1$mobility_by_transit + df1$beds_icu_total + df1$beds_icu_occupied_covid_19 + df1$beds_icu_no_occupied_covid_19 + df1$beds_available_icu_beds_total + df1$vents_total + df1$vents_all_use_covid_19 + df1$vents_non_covid_pts_on_vents + df1$vents_all_available_vents_not_in_use + df1$pct_beds_icu_occupied_covid_19 + df1$pct_beds_icu_no_occupied_covid_19 + df1$pct_beds_available_icu_beds_total + df1$pct_vents_all_use_covid_19 + df1$pct_vents_non_covid_pts_on_vents + df1$pct_vents_all_available_vents_not_in_use
  # model <- df1$date ~ cases + deaths + lat + long + avg_cases_last_week + avg_deaths_last_week + avg_cases_last_2_weeks + avg_deaths_last_2_week + std_cases_last_week + std_deaths_last_week + std_cases_last_2_weeks + std_deaths_last_2_weeks + median_gross_rent + average_household_size + building_permits_number + percent_households_with_computer + percent_households_with_broadband_internet + dollars_per_capita_income_in_past_12_months_2018 + population_per_square_mile + median_household_income + percent_housing_units_in_multi_unit_structures + percent_under_65_without_health_insurance + percent_under_65_with_disability + retail_and_recreation_percent_change_from_baseline + grocery_and_pharmacy_percent_change_from_baseline + parks_percent_change_from_baseline + transit_stations_percent_change_from_baseline + workplaces_percent_change_from_baseline + residential_percent_change_from_baseline + mobility_by_driving + mobility_by_walking + mobility_by_transit + beds_icu_total + beds_icu_occupied_covid_19 + beds_icu_no_occupied_covid_19 + beds_available_icu_beds_total + vents_total + vents_all_use_covid_19 + vents_non_covid_pts_on_vents + vents_all_available_vents_not_in_use + pct_beds_icu_occupied_covid_19 + pct_beds_icu_no_occupied_covid_19 + pct_beds_available_icu_beds_total + pct_vents_all_use_covid_19 + pct_vents_non_covid_pts_on_vents + pct_vents_all_available_vents_not_in_use
  # model <- df1$date ~ avg_cases_by_week + grociery_pharmacy_mobility + parks_mobility + retail_recreation_mobility + transit_stations_mobility + workplace_mobility + driving_mobility_vehicle + transit_mobility_vehicle + walking_mobility_instance + std_last_week_grociery_pharmacy_mobility + std_last_week_park_mobility + std_last_week_retail_recreation_mobility + std_last_week_transit_station_mobility + std_last_week_workplace_mobility
  model <- df1$date ~ cases + deaths + lat + long + avg_cases_last_week + avg_deaths_last_week + avg_cases_last_2_weeks + avg_deaths_last_2_week + std_cases_last_week + std_deaths_last_week + std_cases_last_2_weeks + std_deaths_last_2_weeks + median_gross_rent + average_household_size + building_permits_number + percent_households_with_computer + percent_households_with_broadband_internet + dollars_per_capita_income_in_past_12_months_2018 + population_per_square_mile + median_household_income + percent_housing_units_in_multi_unit_structures + percent_under_65_without_health_insurance + percent_under_65_with_disability + retail_and_recreation_percent_change_from_baseline + grocery_and_pharmacy_percent_change_from_baseline + parks_percent_change_from_baseline + transit_stations_percent_change_from_baseline + workplaces_percent_change_from_baseline + residential_percent_change_from_baseline + mobility_by_driving + mobility_by_walking + mobility_by_transit + beds_icu_total + beds_icu_occupied_covid_19 + beds_icu_no_occupied_covid_19 + beds_available_icu_beds_total + vents_total + vents_all_use_covid_19 + vents_non_covid_pts_on_vents + vents_all_available_vents_not_in_use + pct_beds_icu_occupied_covid_19 + pct_beds_icu_no_occupied_covid_19 + pct_beds_available_icu_beds_total + pct_vents_all_use_covid_19 + pct_vents_non_covid_pts_on_vents + pct_vents_all_available_vents_not_in_use
  glm.D93 <- glm(model, data=data1, family=poisson())
  # print(glm.fit)
  
  sink(file='./out.txt')
  # summary(f)
}

main()